import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'org.jetbrains.kotlin.jvm' version "${kotlin_version}"
	id 'org.jetbrains.kotlin.plugin.serialization' version "${kotlin_version}"
	id 'com.gradleup.shadow' version "${shadow_version}"
}

version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories here
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"server-discord-bot" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	// Fabric
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

	// Kotlin
	implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${project.kotlin_serialization_version}"

	// Kord
	implementation shadow("dev.kord:kord-core:${project.kord_version}")
}

shadowJar {
	archiveClassifier.set("")
	configurations = [project.configurations.shadow]
	relocate("dev.kord", "shadow.dev.kord")
	relocate("kotlinx.coroutines", "shadow.kotlinx.coroutines")
	relocate("kotlinx.serialization", "shadow.kotlinx.serialization")
}

tasks.named("jar") {
	enabled = false
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

kotlin {
	compilerOptions {
		jvmTarget = JvmTarget.JVM_25
	}
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// See https://docs.gradle.org/current/userguide/publishing_maven.html
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
		// Add repositories to publish to here
	}
}