# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod
mod_version=1.0.0
maven_group=com.fooze.serverdiscordbot
archives_base_name=server-discord-bot

# Fabric, https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.155.2+26.2
fabric_kotlin_version=1.13.13+kotlin.2.4.10

# Kotlin
kotlin_version=2.4.10
kotlin_serialization_version=1.11.0

# Kord
kord_version=0.18.1

# Other
shadow_version=9.6.1